"""add username to users

Revision ID: 7b9d122c932b
Revises: a8834121c1e1
Create Date: 2025-12-25 01:17:09.689846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9d122c932b'
down_revision: Union[str, Sequence[str], None] = 'a8834121c1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_category_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_category_id_fkey'), 'expenses', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
