"""Add icon to categories

Revision ID: a8834121c1e1
Revises: 3ebf658763fd
Create Date: 2025-12-11 13:20:20.516982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8834121c1e1'
down_revision: Union[str, Sequence[str], None] = '3ebf658763fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
